routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BonusGameController as AdminBonusGameController;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\ChartController;
use App\Http\Controllers\Admin\DeliveryController;
use App\Http\Controllers\Admin\DumpController;
use App\Http\Controllers\Admin\OptimizationController;
use App\Http\Controllers\Admin\OrderReportController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\StoreRepController;
use App\Http\Controllers\Admin\StoreRepresentativeSettingsController;
use App\Http\Controllers\Admin\TelegramUserController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Mail\MyTestMail;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

//Route::get('/waybill', function () {
//    return view('waybill');
//});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Route::group([
        'prefix' => 'auth',
        'as' => 'auth.'
    ], function () {
        Route::get('/login', [AuthController::class, 'login'])->name('login');
        Route::get('/list', [ProductController::class, 'listReport'])->name('123login');
        Route::get('/game_list', [ProductController::class, 'gameReport'])->name('12sadsa3login');
        Route::post('/authenticate', [AuthController::class, 'authenticate'])->name('authenticate');
    });

    Route::group([
        'middleware' => ['auth:web']
    ], function () {
        Route::group([
            'prefix' => 'brand',
            'as' => 'brand.'
        ], function () {
            Route::get("all", [AdminBrandController::class, 'index'])->name('index');
            Route::get("create", [AdminBrandController::class, 'create'])->name('create');
            Route::post("store", [AdminBrandController::class, 'store'])->name('store');
            Route::get("edit/{brand}", [AdminBrandController::class, 'edit'])->name('edit');
            Route::post("update/{brand}", [AdminBrandController::class, 'update'])->name('update');
            Route::delete("destroy/{brand}", [AdminBrandController::class, 'destroy'])->name('destroy');
            Route::get('filter-brand', [AdminBrandController::class, 'filterBrand']);
            Route::get('all-brand', [AdminBrandController::class, 'allBrand']);
        });

        Route::group([
            'prefix' => 'category',
            'as' => 'category.'
        ], function () {
            Route::get("all", [AdminCategoryController::class, 'allCategory'])->name('allCategory');
            Route::get("create", [AdminCategoryController::class, 'create'])->name('create');
            Route::post("store", [AdminCategoryController::class, 'store'])->name('store');
            Route::get("edit/{category}", [AdminCategoryController::class, 'edit'])->name('edit');
            Route::post("update/{category}", [AdminCategoryController::class, 'update'])->name('update');
            Route::delete("destroy/{category}", [AdminCategoryController::class, 'destroy'])->name('destroy');
            Route::get('filter-category', [AdminCategoryController::class, 'filterCategory']);
        });

        Route::group([
            'prefix' => 'product',
            'as' => 'product.'
        ], function () {
            Route::get("all", [AdminProductController::class, 'index'])->name('index');
            Route::get("create", [AdminProductController::class, 'create'])->name('create');
            Route::post("store", [AdminProductController::class, 'store'])->name('store');
            Route::get("edit/{product}", [AdminProductController::class, 'edit'])->name('edit');
            Route::post("update/{product}", [AdminProductController::class, 'update'])->name('update');
            Route::delete("destroy/{product}", [AdminProductController::class, 'destroy'])->name('destroy');
            Route::get("filter-product", [ProductController::class, 'filterProduct']);
            Route::get("update-remainders", [\App\Http\Controllers\Admin\ProductController::class, 'updateRemaindersPage'])->name('update-remainders');
            Route::post("update-remainders-from-excel", [\App\Http\Controllers\Admin\ProductController::class, 'updateProductRemaindersFromExcel'])->name('updateRemainders');
            Route::get('download-catalogue', [AdminProductController::class, 'downloadCatalogue'])->name('download-catalogue');
        });

        Route::group([
            'prefix' => 'game',
            'as' => 'game.'
        ], function () {
            Route::get("all", [AdminBonusGameController::class, 'allGameHistory'])->name('allGameHistory');
            Route::post("all/search", [AdminBonusGameController::class, 'search'])->name('search');
        });

        Route::group([
            'prefix' => 'store-rep-setting',
            'as' => 'store-rep-settings.'
        ], function () {
            Route::get('all', [StoreRepresentativeSettingsController::class, 'index'])->name('index');
            Route::get('create', [StoreRepresentativeSettingsController::class, 'create'])->name('create');
            Route::delete('destroy/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'destroy'])->name('destroy');
            Route::get('edit/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'edit'])->name('edit');
            Route::post('update/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'update'])->name('update');
        });

        Route::group([
            'prefix' => 'order',
            'as' => 'order.'
        ], function () {
            Route::get('all', [OrderController::class, 'index'])->name('index');
            Route::get('basket/{order}', [OrderController::class, 'basket'])->name('basket');
            Route::get('edit/{order}', [OrderController::class, 'edit'])->name('edit');
            Route::post('update/{order}', [OrderController::class, 'update'])->name('update');
            Route::post('search', [OrderController::class, 'search'])->name('search');
            Route::get('failed-orders', [OrderController::class, 'failedOrders'])->name('failed');
            Route::get('audits', [OrderController::class, 'audits'])->name('audits');
            Route::delete('destroy/{order}', [OrderController::class, 'destroy'])->name('destroy');
            Route::get('{order}/download-single-report', [OrderController::class, 'downloadReport'])->name('download-report');
            Route::get('unknown-basket/{request}', [OrderController::class, 'unknownOrderBasket'])->name('unknown-basket');
        });

        Route::group([
            'prefix' => 'store',
            'as' => 'store.'
        ], function () {
            Route::get('all', [StoreController::class, 'index'])->name('index');
            Route::get('create', [StoreController::class, 'create'])->name('create');
            Route::delete('destroy/{store}', [StoreController::class, 'destroy'])->name('destroy');
            Route::get('edit/{store}', [StoreController::class, 'edit'])->name('edit');
            Route::post('update/{store}', [StoreController::class, 'update'])->name('update');

        });

        Route::group([
            'prefix' => 'user',
            'as' => 'user.'
        ], function () {
            Route::get('all', [UserController::class, 'index'])->name('index');
            Route::get('create', [UserController::class, 'create'])->name('create');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::delete('destroy/{user}', [UserController::class, 'destroy'])->name('destroy');
            Route::get('edit/{user}', [UserController::class, 'edit'])->name('edit');
            Route::post('update/{user}', [UserController::class, 'update'])->name('update');
        });

        Route::group([
            'prefix' => 'order-report',
            'as' => 'order-report.'
        ], function () {
            Route::get('all', [OrderReportController::class, 'index'])->name('index');
            Route::get('show/{date}', [OrderReportController::class, 'show'])->name('show');
            Route::get('download-full/{date}', [OrderReportController::class, 'downloadFull'])->name('download-full');
            Route::get('download-report/{report}', [OrderReportController::class, 'downloadReport'])->name('download-report');
            Route::get('show-report/{report}', [OrderReportController::class, 'showReport'])->name('show-report');
        });

        Route::group([
            'prefix' => 'dump',
            'as' => 'dump.'
        ], function () {
            Route::get('all', [DumpController::class, 'index'])->name('index');
            Route::get('{dumpName}/download', [DumpController::class, 'download'])->name('download');
        });

        Route::group([
            'prefix' => 'delivery-status',
            'as' => 'delivery-status.',
        ], function () {
            Route::get('all', [DeliveryController::class, 'index'])->name('index');
        });

        Route::group([
            'prefix' => 'optimization-results',
            'as' => 'optimization-results.'
        ], function () {
            Route::get('', [OptimizationController::class, 'index'])->name('index');
        });

        Route::get('download-optimized-images', [ProductController::class, 'downloadOptimizedImages']);

        Route::group([
            'prefix' => 'store-rep',
            'as' => 'store-rep.'
        ], function () {

resources/views/admin/layouts/header.blade.php
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-semi-dark navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item">
{{--                    <a class="navbar-brand" href="{{route('admin.index')}}">--}}
                    <a class="navbar-brand" href="#">
                        <img class="brand-logo" alt="robust admin logo" src="{{asset("logo-pm.png")}}">
                        <h3 class="brand-text">{{config('app.name')}}</h3>
                    </a>
                </li>
                <li class="nav-item d-md-none">
                    <a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a>
                </li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu">         </i></a></li>
                    <li class="dropdown nav-item mega-dropdown"><a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">Mega</a>
                    </li>
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>
                    <li class="nav-item nav-search"><a class="nav-link nav-link-search" href="#"><i class="ficon ft-search"></i></a>
                        <div class="search-input">
                            <input class="input" type="text" placeholder="Explore Robust...">
                        </div>
                    </li>
                </ul>
                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <span class="avatar avatar-online">
                              <img src="/robust-admin/app-assets/images/portrait/small/avatar-s-1.png" alt="avatar"><i></i>
                            </span>
                            <span class="user-name">{{Auth::user()->full_name ?? 'admin'}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
{{--                            <form action="{{route('logout')}}" method="post" class="logoutForm">--}}
                            <form action="" method="post" class="logoutForm">
                                @csrf
                            </form>
                            <a class="dropdown-item" href="#" onclick="$('.logoutForm').submit()"><i class="ft-power"></i> Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/admin/layouts/index.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description"
          content="Robust admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template.">
    <meta name="keywords"
          content="admin template, robust admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
    <meta name="author" content="PIXINVENT">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="apple-touch-icon" href="/robust-admin/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="/robust-admin/app-assets/images/ico/favicon.ico">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Muli:300,400,500,700"
        rel="stylesheet">
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="/robust-admin/app-assets/css/vendors.css">

    {{--<link rel="stylesheet" type="text/css" href="/robust-admin/app-assets/vendors/css/tables/datatable/datatables.min.css">--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>

    <!-- END VENDOR CSS-->
    <!-- BEGIN ROBUST CSS-->
    <link rel="stylesheet" type="text/css" href="/robust-admin/app-assets/css/app.css">
    <!-- END ROBUST CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="/robust-admin/app-assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="/robust-admin/app-assets/css/core/colors/palette-gradient.css">

    <!-- END Page Level CSS-->
    {{--deleted--}}
    {{--<link rel="stylesheet" href="/css/jquery.treetable.css" />--}}
    {{--<link rel="stylesheet" href="/css/jquery.treetable.theme.default.css" />--}}

    {{--to add styles in other pages--}}
    @stack('styles')
    <style>
        .storeRepName {
            cursor: pointer;
        }

        .storeRepName:hover {
            box-shadow: 0 0 11px rgba(33, 33, 33, .2);
        }
    </style>

    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="/css/admin-style.css">
    <!-- END Custom CSS-->

</head>
<body class="vertical-layout vertical-menu 2-columns   menu-expanded fixed-navbar"
      data-open="click" data-menu="vertical-menu" data-col="2-columns">
<!-- fixed-top-->
@include('admin.layouts.header')

<!-- ////////////////////////////////////////////////////////////////////////////-->
@include('admin.layouts.sidebar')

<div class="app-content content">
    <div class="content-wrapper">
        @yield('content')
    </div>
</div>
<!-- ////////////////////////////////////////////////////////////////////////////-->

{{--@include('admin.layouts.footer')--}}

<!-- BEGIN VENDOR JS-->
<script src="/robust-admin/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
<script src="/robust-admin/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
<!-- BEGIN VENDOR JS-->
{{--<script src="/robust-admin/app-assets/vendors/js/tables/datatable/datatables.min.js" type="text/javascript"></script>--}}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>

<!-- BEGIN PAGE VENDOR JS-->

@stack('scripts')

<!-- END PAGE VENDOR JS-->
<!-- BEGIN ROBUST JS-->

<script src="/robust-admin/app-assets/js/core/app-menu.js" type="text/javascript"></script>
<script src="/robust-admin/app-assets/js/core/app.js" type="text/javascript"></script>
<script src="/robust-admin/app-assets/js/scripts/customizer.js" type="text/javascript"></script>


<!-- END ROBUST JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="/robust-admin/app-assets/js/scripts/extensions/block-ui.js" type="text/javascript"></script>
<!-- END PAGE LEVEL JS-->
<script src="/robust-admin/app-assets/js/scripts/tables/datatables/datatable-basic.js" type="text/javascript"></script>
<script src="/robust-admin/app-assets/js/scripts/tables/datatables/datatable-api.js" type="text/javascript"></script>

{{--<script src="/js/jquery.treetable.js"></script>--}}
{{--<script src="/js/jquery.jquery-ui.js"></script>--}}

{{--<script src="/js/admin-my.js"></script>--}}

</body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow " data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class=" navigation-header">
                <span data-i18n="nav.category.layouts">Меню</span><i class="ft-more-horizontal ft-minus"
                                                                     data-toggle="tooltip" data-placement="right"
                                                                     data-original-title="Layouts"></i>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.user.index')}}">
                    <i class="fa fa-users"></i><span class="menu-title">Пользователи</span></a>
                <ul class="menu-content">
                    <li>
                        <a class="menu-item" href="{{route('admin.store-rep.index')}}"
                           data-i18n="nav.dash.ecommerce">Торговый</a>
                    </li>
                    <li>
                        <a class="menu-item" href="{{route('admin.user.index', ['filter[role]=2'])}}"
                           data-i18n="nav.dash.ecommerce">Водитель</a>
                    </li>
                    <li>
                        <a class="menu-item" href="{{route('admin.user.index', ['filter[role]=3'])}}"
                           data-i18n="nav.dash.ecommerce">Админ</a>
                    </li>
                    <li>
                        <a class="menu-item" href="{{route('admin.telegram-users.index')}}"
                           data-i18n="nav.dash.ecommerce">Телеграм пользователи</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.brand.index')}}"><i class="fa fa-shopping-basket"></i><span class="menu-title"
                                                                                                    data-i18n="nav.changelog.main">Брэнды</span></a>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.order.index')}}"><i class="fa fa-ticket"></i><span class="menu-title"
                                                                                           data-i18n="nav.changelog.main">Заказы</span></a>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.order.index')}}">
                    <i class="fa fa-users"></i><span class="menu-title">Заказы</span></a>
                <ul class="menu-content">
                    <li>
                        <a class="menu-item" href="{{route('admin.order.index', ['filter[trashed]=only'])}}"
                           data-i18n="nav.dash.ecommerce">Удаленные</a>
                    </li>
                    <li>
                        <a class="menu-item" href="{{route('admin.order.index', ['filter[status]=1'])}}"
                           data-i18n="nav.dash.ecommerce">Готовы к доставке</a>
                    </li>
                    <li>
                        <a class="menu-item" href="#"
                           data-i18n="nav.dash.ecommerce">В доставке</a>
                    </li>
                    <li>
                        <a class="menu-item" href="#"
                           data-i18n="nav.dash.ecommerce">Доставлено</a>
                    </li>
                    <li>
                        <a class="menu-item" href="#"
                           data-i18n="nav.dash.ecommerce">Неизвестно</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                {{--                <a href="{{route('admin.category.index')}}"><i class="fa fa-tasks"></i><span class="menu-title" data-i18n="nav.changelog.main">Категории</span></a>--}}
            </li>
            <li class="nav-item">
                <a href="{{route('admin.category.allCategory')}}"><i class="fa fa-object-group"></i><span
                        class="menu-title" data-i18n="nav.changelog.main">Категории</span></a>
            </li>

            <li class="nav-item">
                <a href="{{route('admin.store-rep-settings.index')}}"><i class="fa fa-gear"></i><span class="menu-title"
                                                                                                      data-i18n="nav.changelog.main">Настройки</span></a>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.product.index')}}"><i class="fa fa-shopping-basket"></i><span class="menu-title"
                                                                                                      data-i18n="nav.changelog.main">Продукты</span></a>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.store.index')}}"><i class="fa fa-shopping-cart"></i><span class="menu-title"
                                                                                                  data-i18n="nav.changelog.main">Торг.точки</span></a>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.game.allGameHistory')}}"><i class="ft-box"></i><span class="menu-title"
                                                                                             data-i18n="nav.changelog.main">Истории игр</span></a>
            </li>
            {{-- <li class="nav-item">
                 <a href="{{route('admin.order-report.index')}}"><i class="ft-box"></i><span class="menu-title" data-i18n="nav.changelog.main">Отчет</span></a>
             </li> --}}
            <li class="nav-item">
                {{--                <a href="{{route('admin.category.index')}}"><i class="fa fa-building"></i><span class="menu-title" data-i18n="nav.changelog.main">Категории</span></a>--}}
            </li>
            <li class="nav-item">
                <a href="{{route('admin.order.failed')}}">Не состоявшиеся заказы</a>
            </li>
            <li class="nav-item">
                <a href="{{route('admin.order.audits')}}">Аудит заказов</a>
            </li>
        </ul>
    </div>
</div>