routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BonusGameController as AdminBonusGameController;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\ChartController;
use App\Http\Controllers\Admin\DeliveryController;
use App\Http\Controllers\Admin\DumpController;
use App\Http\Controllers\Admin\OptimizationController;
use App\Http\Controllers\Admin\OrderReportController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\StoreRepController;
use App\Http\Controllers\Admin\StoreRepresentativeSettingsController;
use App\Http\Controllers\Admin\TelegramUserController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Mail\MyTestMail;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

//Route::get('/waybill', function () {
//    return view('waybill');
//});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Route::group([
        'prefix' => 'auth',
        'as' => 'auth.'
    ], function () {
        Route::get('/login', [AuthController::class, 'login'])->name('login');
        Route::get('/list', [ProductController::class, 'listReport'])->name('123login');
        Route::get('/game_list', [ProductController::class, 'gameReport'])->name('12sadsa3login');
        Route::post('/authenticate', [AuthController::class, 'authenticate'])->name('authenticate');
    });

    Route::group([
        'middleware' => ['auth:web']
    ], function () {
        Route::group([
            'prefix' => 'brand',
            'as' => 'brand.'
        ], function () {
            Route::get("all", [AdminBrandController::class, 'index'])->name('index');
            Route::get("create", [AdminBrandController::class, 'create'])->name('create');
            Route::post("store", [AdminBrandController::class, 'store'])->name('store');
            Route::get("edit/{brand}", [AdminBrandController::class, 'edit'])->name('edit');
            Route::post("update/{brand}", [AdminBrandController::class, 'update'])->name('update');
            Route::delete("destroy/{brand}", [AdminBrandController::class, 'destroy'])->name('destroy');
            Route::get('filter-brand', [AdminBrandController::class, 'filterBrand']);
            Route::get('all-brand', [AdminBrandController::class, 'allBrand']);
        });

        Route::group([
            'prefix' => 'category',
            'as' => 'category.'
        ], function () {
            Route::get("all", [AdminCategoryController::class, 'allCategory'])->name('allCategory');
            Route::get("create", [AdminCategoryController::class, 'create'])->name('create');
            Route::post("store", [AdminCategoryController::class, 'store'])->name('store');
            Route::get("edit/{category}", [AdminCategoryController::class, 'edit'])->name('edit');
            Route::post("update/{category}", [AdminCategoryController::class, 'update'])->name('update');
            Route::delete("destroy/{category}", [AdminCategoryController::class, 'destroy'])->name('destroy');
            Route::get('filter-category', [AdminCategoryController::class, 'filterCategory']);
        });

        Route::group([
            'prefix' => 'product',
            'as' => 'product.'
        ], function () {
            Route::get("all", [AdminProductController::class, 'index'])->name('index');
            Route::get("create", [AdminProductController::class, 'create'])->name('create');
            Route::post("store", [AdminProductController::class, 'store'])->name('store');
            Route::get("edit/{product}", [AdminProductController::class, 'edit'])->name('edit');
            Route::post("update/{product}", [AdminProductController::class, 'update'])->name('update');
            Route::delete("destroy/{product}", [AdminProductController::class, 'destroy'])->name('destroy');
            Route::get("filter-product", [ProductController::class, 'filterProduct']);
            Route::get("update-remainders", [\App\Http\Controllers\Admin\ProductController::class, 'updateRemaindersPage'])->name('update-remainders');
            Route::post("update-remainders-from-excel", [\App\Http\Controllers\Admin\ProductController::class, 'updateProductRemaindersFromExcel'])->name('updateRemainders');
            Route::get('download-catalogue', [AdminProductController::class, 'downloadCatalogue'])->name('download-catalogue');
        });

        Route::group([
            'prefix' => 'game',
            'as' => 'game.'
        ], function () {
            Route::get("all", [AdminBonusGameController::class, 'allGameHistory'])->name('allGameHistory');
            Route::post("all/search", [AdminBonusGameController::class, 'search'])->name('search');
        });

        Route::group([
            'prefix' => 'store-rep-setting',
            'as' => 'store-rep-settings.'
        ], function () {
            Route::get('all', [StoreRepresentativeSettingsController::class, 'index'])->name('index');
            Route::get('create', [StoreRepresentativeSettingsController::class, 'create'])->name('create');
            Route::delete('destroy/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'destroy'])->name('destroy');
            Route::get('edit/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'edit'])->name('edit');
            Route::post('update/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'update'])->name('update');
        });

        Route::group([
            'prefix' => 'order',
            'as' => 'order.'
        ], function () {
            Route::get('all', [OrderController::class, 'index'])->name('index');
            Route::get('basket/{order}', [OrderController::class, 'basket'])->name('basket');
            Route::get('edit/{order}', [OrderController::class, 'edit'])->name('edit');
            Route::post('update/{order}', [OrderController::class, 'update'])->name('update');
            Route::post('search', [OrderController::class, 'search'])->name('search');
            Route::get('failed-orders', [OrderController::class, 'failedOrders'])->name('failed');
            Route::get('audits', [OrderController::class, 'audits'])->name('audits');
            Route::delete('destroy/{order}', [OrderController::class, 'destroy'])->name('destroy');
            Route::get('{order}/download-single-report', [OrderController::class, 'downloadReport'])->name('download-report');
            Route::get('unknown-basket/{request}', [OrderController::class, 'unknownOrderBasket'])->name('unknown-basket');
        });

        Route::group([
            'prefix' => 'store',
            'as' => 'store.'
        ], function () {
            Route::get('all', [StoreController::class, 'index'])->name('index');
            Route::get('create', [StoreController::class, 'create'])->name('create');
            Route::delete('destroy/{store}', [StoreController::class, 'destroy'])->name('destroy');
            Route::get('edit/{store}', [StoreController::class, 'edit'])->name('edit');
            Route::post('update/{store}', [StoreController::class, 'update'])->name('update');

        });

        Route::group([
            'prefix' => 'user',
            'as' => 'user.'
        ], function () {
            Route::get('all', [UserController::class, 'index'])->name('index');
            Route::get('create', [UserController::class, 'create'])->name('create');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::delete('destroy/{user}', [UserController::class, 'destroy'])->name('destroy');
            Route::get('edit/{user}', [UserController::class, 'edit'])->name('edit');
            Route::post('update/{user}', [UserController::class, 'update'])->name('update');
        });

        Route::group([
            'prefix' => 'order-report',
            'as' => 'order-report.'
        ], function () {
            Route::get('all', [OrderReportController::class, 'index'])->name('index');
            Route::get('show/{date}', [OrderReportController::class, 'show'])->name('show');
            Route::get('download-full/{date}', [OrderReportController::class, 'downloadFull'])->name('download-full');
            Route::get('download-report/{report}', [OrderReportController::class, 'downloadReport'])->name('download-report');
            Route::get('show-report/{report}', [OrderReportController::class, 'showReport'])->name('show-report');
        });

        Route::group([
            'prefix' => 'dump',
            'as' => 'dump.'
        ], function () {
            Route::get('all', [DumpController::class, 'index'])->name('index');
            Route::get('{dumpName}/download', [DumpController::class, 'download'])->name('download');
        });

        Route::group([
            'prefix' => 'delivery-status',
            'as' => 'delivery-status.',
        ], function () {
            Route::get('all', [DeliveryController::class, 'index'])->name('index');
        });

        Route::group([
            'prefix' => 'optimization-results',
            'as' => 'optimization-results.'
        ], function () {
            Route::get('', [OptimizationController::class, 'index'])->name('index');
        });

        Route::get('download-optimized-images', [ProductController::class, 'downloadOptimizedImages']);

        Route::group([
            'prefix' => 'store-rep',
            'as' => 'store-rep.'
        ], function () {

app/Models/Brand.php
<?php

namespace App\Models;

use App\Scopes\EnabledScope;
use App\Traits\ModelTableNameTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory, ModelTableNameTrait;

    protected static function booted()
    {
        static::addGlobalScope(new EnabledScope());
    }

    protected $guarded = [
        'id'
    ];

    protected $fillable = [
        'name',
        'active'
    ];

    public function productsEnabled()
    {
        return $this->hasMany(Product::class,'brand_id','id')->where('enabled',true);
    }



}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Brand;
use App\Scopes\EnabledScope;
use Doctrine\DBAL\Query\QueryBuilder;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    public function index()
    {
        $brands = Brand::withoutGlobalScope(EnabledScope::class)->get();
        return view('admin.brands.index',compact('brands'));
    }

    public function create()
    {
        $brands = Brand::all();
        return view('admin.brands.create2',compact('brands'));
    }

    public function store(Request $request, Brand $brand)
    {
        $brand->name = $request->name;
        $brand->active = $request->active;
        $brand->save();

        return redirect()->route('admin.brand.index');

    }

    public function edit(Brand $brand)
    {
        return view('admin.brands.edit',[
            'brand' => $brand
        ]);
    }

    public function update(Request $request, Brand $brand)
    {

        $brand->name = $request->input('name');
        $brand->save();

        return redirect()->back()->withSuccess('Брэнд успешно изменено');
    }

    public function destroy(Brand $brand)
    {
        $brand->delete();

        return redirect()->back()->withSuccess('Брэнд успешно удалена');
    }

    public function allBrand()
    {
        $brands = Brand::all();
        return response()->json($brands);
    }

    public function filterBrand()
    {
        $brands = QueryBuilder::for(Brand::class)
            ->allowedFilters(['name'])
            ->paginate(10);

        return $brands ;
    }
}

app/Http/Controllers/BrandController.php
<?php


namespace App\Http\Controllers;


use App\Models\Brand;
use App\Traits\CustomResponse;
use Illuminate\Http\JsonResponse;

class BrandController
{
    use CustomResponse;

    public function index()
    {
        $brands = Brand::all();
        return  $this->cresponse('ok',$brands,JsonResponse::HTTP_OK);
    }

}

resources/views/admin/brands/edit.blade.php
@extends('admin.layouts.index')

@section('title')
    Редактировать брэнд
@endsection

@section('content')
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="horz-layout-card-center">Редактировать брэнд: {{ $brand->name }}</h4>
                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-content collpase show">
                    <div class="card-body">
                        <form class="form form-horizontal" action="{{ route('admin.brand.update',$brand->id)}}"
                              method="post"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="form form-horizontal">
                                <ul class="nav nav-tabs">
                                    {{--                                    @include('admin.form_blocks.tab.nav',['name'=>'tabGeneralInfo','title'=>'Общие',])--}}
                                    {{--                                    @include('admin.form_blocks.tab.nav',['name'=>'tabSeo','title'=>'SEO'])--}}
                                    {{--                                    @include('admin.form_blocks.tab.nav',['name'=>'tabImages','title'=>'Картинки'])--}}
                                    @include('admin.form_blocks.tab.nav',['name'=>'tabBrands','title'=>'Брэнды'])
                                    {{--                                    @include('admin.form_blocks.tab.nav',['name'=>'tabCities','title'=>'Города'])--}}
                                </ul>
                                <div class="tab-content px-1 pt-1  border-grey border-lighten-2 border-0-top">

                                    {{--                                    @component('admin.form_blocks.tab.content',['name'=>'tabGeneralInfo','active'=>'1'])--}}
                                    {{--                                        <div--}}
                                    {{--                                            class="tab-content  px-1 pt-1 ">--}}
                                    {{--                                            @include('admin.form_blocks.input',['type'=>'text','label'=>'Заголовок','name'=>'title', 'value'=> $category->title])--}}
                                    {{--                                            @include('admin.form_blocks.input',['type'=>'text','label'=>'Название','name'=>'name', 'generateSlug' => true, 'value'=> $category->name])--}}
                                    {{--                                            @include('admin.form_blocks.textarea',['label'=>'Описание','name'=>'category', 'summernote'=>1, 'text'=>$category->text])--}}
                                    {{--                                            @include('admin.form_blocks.textarea',['label'=>'Краткое описание','name'=>'category', 'placeholder'=> 'Краткое описание', 'text'=>$category->text])--}}
                                    {{--                                        </div>--}}
                                    {{--                                    @endcomponent--}}
                                    {{--                                    @component('admin.form_blocks.tab.content',['name'=>'tabSeo',])--}}
                                    {{--                                        <div class="tab-content  px-1 pt-1 ">--}}
                                    {{--                                            @include('admin.form_blocks.input',['type'=>'text','label'=>'Slug - ссылка','name'=>'slug', 'value'=> $category->slug, 'id' => 'slug'])--}}
                                    {{--                                            @include('admin.form_blocks.input',['type'=>'text','label'=>'Seo - заголовок','name'=>'seo_title', 'value' => $category->seo_title])--}}
                                    {{--                                            @include('admin.form_blocks.textarea',['label'=>'Seo Описание','name'=>'seo_description', 'text'=>$category->seo_description])--}}
                                    {{--                                            @include('admin.form_blocks.input',['type'=>'checkbox','label'=>'Популярная категория в поиске?','name'=>'popular_in_search','value'=>$category->popular_in_search,'id'=>'main-page-display'])--}}
                                    {{--                                        </div>--}}
                                    {{--                                    @endcomponent--}}
                                    {{--                                    @component('admin.form_blocks.tab.content',['name'=>'tabImages'])--}}
                                    {{--                                        @include('admin.form_blocks.ajax_image',['label'=>'Главная картинка','name'=>'image','type'=>'file'])--}}
                                    {{--                                        @include('admin.form_blocks.file',['label'=>'Картинки','name'=>'images[]','load'=>'','multiple'=>''])--}}
                                    {{--                                    @endcomponent--}}

                                    @if (session('success'))
                                        <div class="alert alert-success" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                            <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                                        </div>
                                    @endif

                                    @component('admin.form_blocks.tab.content',['name'=>'tabBrands'])
                                        <div class="tab-content  px-1 pt-1 ">
                                            <div>
                                                <input type="text" value="{{ $brand->name }}" name="name" class="form-control">
                                            </div>
                                        </div>
                                    @endcomponent

                                    {{--                                    @foreach($categories as $category)--}}
                                    {{--                                        <tr>--}}
                                    {{--                                            <td class="pk_id">{{ $category->id }}</td>--}}
                                    {{--                                            <td>@include('admin.form_blocks.imageView',['image'=>$category->mainImagePath])</td>--}}
                                    {{--                                            <td>{{ $category->parent ? '<a href=#>'. $category->parent->title .'</a>' : null }}</td>--}}
                                    {{--                                            <td>{{ $category->slug }}</td>--}}
                                    {{--                                            <td>{{$category->title}}</td>--}}
                                    {{--                                            <td>{{ $category->created_at }}</td>--}}
                                    {{--                                            <td>--}}
                                    {{--                                                @include('admin.form_blocks.actions',['route_edit'=>route('admin.category.edit', $category['id']),'route_destroy'=>route('admin.category.destroy', $category['id'])])--}}
                                    {{--                                            </td>--}}
                                    {{--                                        </tr>--}}
                                    {{--                                    @endforeach--}}
                                </div>
                            </div>
                            @include('admin.form_blocks.submit',['title'=>'Изменить'])
                            @include('admin.form_blocks.error')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            function generateSlug(value) {
                console.log(value);
                $.ajax({
                    type: 'POST',
                    url: '/admin/product/generate_slug',
                    data: {
                        slug: value,
                    },
                    success: function (response) {
                        $('#slug').val(response);
                    },
                });
            }
        </script>
    @endpush

@endsection

{{--<script type="text/javascript">--}}
{{--    $.ajaxSetup({--}}
{{--        headers: {--}}
{{--            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')--}}
{{--        }--}}
{{--    });--}}
{{--</script>--}}

{{--<script>--}}

{{--    --}}

{{--    $('#myForm a').click(function (e) {--}}
{{--        e.preventDefault();--}}
{{--        $(this).tab('show');--}}
{{--    });--}}

{{--    function addPhoto() {--}}

{{--        var formData = new FormData();--}}
{{--        formData.append('file', $('#sendImage')[0].files[0]);--}}
{{--        $.ajax({--}}
{{--            type: "POST",--}}
{{--            url: '{{route('admin.ajax.add_image')}}',--}}
{{--            data: formData,--}}
{{--            processData: false,  // Important!--}}
{{--            contentType: false,--}}
{{--            contentType: false,--}}
{{--            cache: false,--}}

{{--            success: function (response) {--}}
{{--                console.log(response);--}}
{{--                let imageContainer = document.getElementById('image-container');--}}
{{--                console.log(response['url']);--}}
{{--                let image = document.createElement("img");--}}
{{--                let imgId = document.getElementById("imageId");--}}
{{--                imgId.value = response['id'];--}}
{{--                console.log(response['id']);--}}
{{--                image.setAttribute('width', 500);--}}
{{--                image.setAttribute('src', response['url']);--}}
{{--                image.setAttribute('height', 'auto');--}}
{{--                imageContainer.appendChild(image);--}}

{{--            },--}}
{{--        });--}}

{{--    }--}}

{{--    document.getElementById("addPhoto").addEventListener("click", addPhoto);--}}

{{--</script>--}}
{{--</body>--}}
{{--</html>--}}

resources/views/admin/brands/index.blade.php
@extends('admin.layouts.index')

@section('title')
    Брэнды
@endsection

@section('content')
    <section id="configuration">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Брэнды</h4>
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div style="margin-left: 2%" class="crud-create">
                        <a href="{{route('admin.brand.create')}}" type="button" class="btn btn-success btn-min-width"><i style="margin-right: 5px" class="fa fa-check"></i>Создать</a>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard table-responsive">
                            <table id="categoriesTable" class="table table-striped table-bordered sorted_table">
                                <thead>
                                <tr>
                                    <th class="defaultSort">ID</th>
                                    <th>Actions</th>
                                    <th>Картинка</th>
                                    <th>Наименование</th>
                                    <th>Создано</th>
                                    <th>Доступен</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($brands as $brand)
                                    <tr>
                                        <td class="pk_id">{{ $brand->id }}</td>
                                        <td>
                                            @include('admin.form_blocks.actions',['route_edit'=>route('admin.brand.edit',['brand' => $brand->id]),'route_destroy'=>route('admin.brand.destroy', ['brand' => $brand->id])])
                                        </td>
                                        <td></td>
                                        <td>{{$brand->name}}</td>
                                        <td>{{ $brand->created_at }}</td>
                                        <td>{{ $brand->enabled ? 'Да' : 'Нет' }}</td>

                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')

    <script src="/robust-admin/app-assets/js/scripts/extensions/jquery-sortable.js" type="text/javascript"></script>

    <script>

        $('.destroyFormSubmit').click(function() {
            return confirm('Вы действительно хотите удалить?');
        });

        /*datatables*/
        var table = $('#categoriesTable').dataTable({
            order: [[ $('th.defaultSort').index(),  'asc' ]],
            aLengthMenu: [7, 25, 50, 100],
        });

        // Sortable rows
        $('.sorted_table').sortable({
            containerSelector: 'table',
            itemPath: '> tbody',
            itemSelector: 'tr',
            placeholder: '<tr class="placeholder"/>',
            onDrop: function ($item, container, _super, event) {
                $item.removeClass(container.group.options.draggedClass).removeAttr("style");
                $("body").removeClass(container.group.options.bodyClass);
                sortdb();
            }
        });

        function sortdb() {
            var table = $('.sorted_table tbody tr');
            $perPage = $("select[name=categoriesTable_length]").val();
            $first_position = parseInt(table.find('td.position').eq(0).text())-1;
            $start_pos = parseInt($first_position/$perPage)*$perPage;
            $pos = $start_pos;
            table.each(function(index) {
                $(this).find('td.position').text(++$pos);
                $id = $(this).find('td.pk_id').text();
            });

        }
    </script>

@endpush


@push('styles')

    <style>
        .dragged {
            position: absolute;
            top: 0;
            opacity: 0.5;
            z-index: 2000;
        }

        .placeholder:before {
            content: "";
            position: relative;
            width: 0;
            height: 0;
            border: 5px solid transparent;
            border-top-color: red;
            top: -6px;
            margin-left: -5px;
            border-bottom: none;
        }
    </style>

@endpush

resources/views/admin/brands/test.blade.php
{{--@extends('admin.layouts.index')--}}

@section('title')
    Добавить категорию
@endsection