routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BonusGameController as AdminBonusGameController;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\ChartController;
use App\Http\Controllers\Admin\DeliveryController;
use App\Http\Controllers\Admin\DumpController;
use App\Http\Controllers\Admin\OptimizationController;
use App\Http\Controllers\Admin\OrderReportController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\StoreRepController;
use App\Http\Controllers\Admin\StoreRepresentativeSettingsController;
use App\Http\Controllers\Admin\TelegramUserController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Mail\MyTestMail;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

//Route::get('/waybill', function () {
//    return view('waybill');
//});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Route::group([
        'prefix' => 'auth',
        'as' => 'auth.'
    ], function () {
        Route::get('/login', [AuthController::class, 'login'])->name('login');
        Route::get('/list', [ProductController::class, 'listReport'])->name('123login');
        Route::get('/game_list', [ProductController::class, 'gameReport'])->name('12sadsa3login');
        Route::post('/authenticate', [AuthController::class, 'authenticate'])->name('authenticate');
    });

    Route::group([
        'middleware' => ['auth:web']
    ], function () {
        Route::group([
            'prefix' => 'brand',
            'as' => 'brand.'
        ], function () {
            Route::get("all", [AdminBrandController::class, 'index'])->name('index');
            Route::get("create", [AdminBrandController::class, 'create'])->name('create');
            Route::post("store", [AdminBrandController::class, 'store'])->name('store');
            Route::get("edit/{brand}", [AdminBrandController::class, 'edit'])->name('edit');
            Route::post("update/{brand}", [AdminBrandController::class, 'update'])->name('update');
            Route::delete("destroy/{brand}", [AdminBrandController::class, 'destroy'])->name('destroy');
            Route::get('filter-brand', [AdminBrandController::class, 'filterBrand']);
            Route::get('all-brand', [AdminBrandController::class, 'allBrand']);
        });

        Route::group([
            'prefix' => 'category',
            'as' => 'category.'
        ], function () {
            Route::get("all", [AdminCategoryController::class, 'allCategory'])->name('allCategory');
            Route::get("create", [AdminCategoryController::class, 'create'])->name('create');
            Route::post("store", [AdminCategoryController::class, 'store'])->name('store');
            Route::get("edit/{category}", [AdminCategoryController::class, 'edit'])->name('edit');
            Route::post("update/{category}", [AdminCategoryController::class, 'update'])->name('update');
            Route::delete("destroy/{category}", [AdminCategoryController::class, 'destroy'])->name('destroy');
            Route::get('filter-category', [AdminCategoryController::class, 'filterCategory']);
        });

        Route::group([
            'prefix' => 'product',
            'as' => 'product.'
        ], function () {
            Route::get("all", [AdminProductController::class, 'index'])->name('index');
            Route::get("create", [AdminProductController::class, 'create'])->name('create');
            Route::post("store", [AdminProductController::class, 'store'])->name('store');
            Route::get("edit/{product}", [AdminProductController::class, 'edit'])->name('edit');
            Route::post("update/{product}", [AdminProductController::class, 'update'])->name('update');
            Route::delete("destroy/{product}", [AdminProductController::class, 'destroy'])->name('destroy');
            Route::get("filter-product", [ProductController::class, 'filterProduct']);
            Route::get("update-remainders", [\App\Http\Controllers\Admin\ProductController::class, 'updateRemaindersPage'])->name('update-remainders');
            Route::post("update-remainders-from-excel", [\App\Http\Controllers\Admin\ProductController::class, 'updateProductRemaindersFromExcel'])->name('updateRemainders');
            Route::get('download-catalogue', [AdminProductController::class, 'downloadCatalogue'])->name('download-catalogue');
        });

        Route::group([
            'prefix' => 'game',
            'as' => 'game.'
        ], function () {
            Route::get("all", [AdminBonusGameController::class, 'allGameHistory'])->name('allGameHistory');
            Route::post("all/search", [AdminBonusGameController::class, 'search'])->name('search');
        });

        Route::group([
            'prefix' => 'store-rep-setting',
            'as' => 'store-rep-settings.'
        ], function () {
            Route::get('all', [StoreRepresentativeSettingsController::class, 'index'])->name('index');
            Route::get('create', [StoreRepresentativeSettingsController::class, 'create'])->name('create');
            Route::delete('destroy/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'destroy'])->name('destroy');
            Route::get('edit/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'edit'])->name('edit');
            Route::post('update/{storeRepresentativeSetting}', [StoreRepresentativeSettingsController::class, 'update'])->name('update');
        });

        Route::group([
            'prefix' => 'order',
            'as' => 'order.'
        ], function () {
            Route::get('all', [OrderController::class, 'index'])->name('index');
            Route::get('basket/{order}', [OrderController::class, 'basket'])->name('basket');
            Route::get('edit/{order}', [OrderController::class, 'edit'])->name('edit');
            Route::post('update/{order}', [OrderController::class, 'update'])->name('update');
            Route::post('search', [OrderController::class, 'search'])->name('search');
            Route::get('failed-orders', [OrderController::class, 'failedOrders'])->name('failed');
            Route::get('audits', [OrderController::class, 'audits'])->name('audits');
            Route::delete('destroy/{order}', [OrderController::class, 'destroy'])->name('destroy');
            Route::get('{order}/download-single-report', [OrderController::class, 'downloadReport'])->name('download-report');
            Route::get('unknown-basket/{request}', [OrderController::class, 'unknownOrderBasket'])->name('unknown-basket');
        });

        Route::group([
            'prefix' => 'store',
            'as' => 'store.'
        ], function () {
            Route::get('all', [StoreController::class, 'index'])->name('index');
            Route::get('create', [StoreController::class, 'create'])->name('create');
            Route::delete('destroy/{store}', [StoreController::class, 'destroy'])->name('destroy');
            Route::get('edit/{store}', [StoreController::class, 'edit'])->name('edit');
            Route::post('update/{store}', [StoreController::class, 'update'])->name('update');

        });

        Route::group([
            'prefix' => 'user',
            'as' => 'user.'
        ], function () {
            Route::get('all', [UserController::class, 'index'])->name('index');
            Route::get('create', [UserController::class, 'create'])->name('create');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::delete('destroy/{user}', [UserController::class, 'destroy'])->name('destroy');
            Route::get('edit/{user}', [UserController::class, 'edit'])->name('edit');
            Route::post('update/{user}', [UserController::class, 'update'])->name('update');
        });

        Route::group([
            'prefix' => 'order-report',
            'as' => 'order-report.'
        ], function () {
            Route::get('all', [OrderReportController::class, 'index'])->name('index');
            Route::get('show/{date}', [OrderReportController::class, 'show'])->name('show');
            Route::get('download-full/{date}', [OrderReportController::class, 'downloadFull'])->name('download-full');
            Route::get('download-report/{report}', [OrderReportController::class, 'downloadReport'])->name('download-report');
            Route::get('show-report/{report}', [OrderReportController::class, 'showReport'])->name('show-report');
        });

        Route::group([
            'prefix' => 'dump',
            'as' => 'dump.'
        ], function () {
            Route::get('all', [DumpController::class, 'index'])->name('index');
            Route::get('{dumpName}/download', [DumpController::class, 'download'])->name('download');
        });

        Route::group([
            'prefix' => 'delivery-status',
            'as' => 'delivery-status.',
        ], function () {
            Route::get('all', [DeliveryController::class, 'index'])->name('index');
        });

        Route::group([
            'prefix' => 'optimization-results',
            'as' => 'optimization-results.'
        ], function () {
            Route::get('', [OptimizationController::class, 'index'])->name('index');
        });

        Route::get('download-optimized-images', [ProductController::class, 'downloadOptimizedImages']);

        Route::group([
            'prefix' => 'store-rep',
            'as' => 'store-rep.'
        ], function () {

app/Http/Controllers/Admin/DumpController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class DumpController extends Controller
{
    const DUMPS_DIR = '/home/dev-pd/dumps/';

    const TEST_DIR = '/var/www/boszhan-delivery-service/repositories/boszhan_delivery/storage/app/public/catalogues/';

    public function index()
    {
        $dumps = scandir(self::DUMPS_DIR);

        foreach ($dumps as $key => $dump) {
            if (!str_starts_with($dump,'backup')) {
                unset($dumps[$key]);
            }
        }
        return view('admin.dumps.index', compact('dumps'));
    }

    public function download($dumpName)
    {
        $file = self::DUMPS_DIR.$dumpName;

        if (file_exists($file)) {
            return response()->download($file, $dumpName);
        }
    }
}

resources/views/admin/dumps/index.blade.php
@extends('admin.layouts.index')

@section('title')
    Бекапы базы данных
@endsection

@section('content')
    <section id="configuration">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Бекапы</h4>
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard table-responsive">
                            <table id="categoriesTable" class="table table-striped table-bordered sorted_table">
                                <thead>
                                <tr>
                                    <th class="defaultSort">Нумерация</th>
                                    <th>Название</th>
                                    <th>Создано</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($dumps as $key=>$dump)
                                    <tr>
                                        <td class="pk_id">{{ $key }}</td>
                                        <td>{{$dump}}</td>
                                        <td>{{\Carbon\Carbon::createFromFormat('YmdHis',str_replace('.sql','',explode('_', $dump)[1]))->format('Y-m-d')}}</td>
                                        <td>
                                            @include('admin.form_blocks.actions',['route_download'=>route('admin.dump.download',['dumpName' => $dump]), 'destroy_disable' => true])
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection